/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppStaffRouteImport } from './routes/app.staff'
import { Route as MfaChallengeRouteImport } from './routes/mfa.challenge'
import { Route as MfaSetupRouteImport } from './routes/mfa.setup'
import { Route as StaffActivateRouteImport } from './routes/staff.activate'
import { Route as ApiIntakePublishedFormIdRouteImport } from './routes/api.intake.$publishedFormId'
import { Route as ApiWorkersMaintenanceRouteImport } from './routes/api.workers.maintenance'
import { Route as ApiWorkersOutboxRouteImport } from './routes/api.workers.outbox'
import { Route as AppEnquiriesIndexRouteImport } from './routes/app.enquiries.index'
import { Route as AppEnquiriesIdRouteImport } from './routes/app.enquiries.$id'
import { Route as IntakePublishedFormIdIndexRouteImport } from './routes/intake.$publishedFormId.index'
import { Route as IntakePublishedFormIdSubmittedRouteImport } from './routes/intake.$publishedFormId.submitted'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const MfaChallengeRoute = MfaChallengeRouteImport.update({
  id: '/mfa/challenge',
  path: '/mfa/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaSetupRoute = MfaSetupRouteImport.update({
  id: '/mfa/setup',
  path: '/mfa/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffActivateRoute = StaffActivateRouteImport.update({
  id: '/staff/activate',
  path: '/staff/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntakePublishedFormIdRoute =
  ApiIntakePublishedFormIdRouteImport.update({
    id: '/api/intake/$publishedFormId',
    path: '/api/intake/$publishedFormId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkersMaintenanceRoute = ApiWorkersMaintenanceRouteImport.update({
  id: '/api/workers/maintenance',
  path: '/api/workers/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkersOutboxRoute = ApiWorkersOutboxRouteImport.update({
  id: '/api/workers/outbox',
  path: '/api/workers/outbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEnquiriesIndexRoute = AppEnquiriesIndexRouteImport.update({
  id: '/enquiries/',
  path: '/enquiries/',
  getParentRoute: () => AppRoute,
} as any)
const AppEnquiriesIdRoute = AppEnquiriesIdRouteImport.update({
  id: '/enquiries/$id',
  path: '/enquiries/$id',
  getParentRoute: () => AppRoute,
} as any)
const IntakePublishedFormIdIndexRoute =
  IntakePublishedFormIdIndexRouteImport.update({
    id: '/intake/$publishedFormId/',
    path: '/intake/$publishedFormId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntakePublishedFormIdSubmittedRoute =
  IntakePublishedFormIdSubmittedRouteImport.update({
    id: '/intake/$publishedFormId/submitted',
    path: '/intake/$publishedFormId/submitted',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/staff': typeof AppStaffRoute
  '/mfa/challenge': typeof MfaChallengeRoute
  '/mfa/setup': typeof MfaSetupRoute
  '/staff/activate': typeof StaffActivateRoute
  '/api/intake/$publishedFormId': typeof ApiIntakePublishedFormIdRoute
  '/api/workers/maintenance': typeof ApiWorkersMaintenanceRoute
  '/api/workers/outbox': typeof ApiWorkersOutboxRoute
  '/app/enquiries/$id': typeof AppEnquiriesIdRoute
  '/intake/$publishedFormId/submitted': typeof IntakePublishedFormIdSubmittedRoute
  '/app/enquiries/': typeof AppEnquiriesIndexRoute
  '/intake/$publishedFormId/': typeof IntakePublishedFormIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/staff': typeof AppStaffRoute
  '/mfa/challenge': typeof MfaChallengeRoute
  '/mfa/setup': typeof MfaSetupRoute
  '/staff/activate': typeof StaffActivateRoute
  '/api/intake/$publishedFormId': typeof ApiIntakePublishedFormIdRoute
  '/api/workers/maintenance': typeof ApiWorkersMaintenanceRoute
  '/api/workers/outbox': typeof ApiWorkersOutboxRoute
  '/app/enquiries/$id': typeof AppEnquiriesIdRoute
  '/intake/$publishedFormId/submitted': typeof IntakePublishedFormIdSubmittedRoute
  '/app/enquiries': typeof AppEnquiriesIndexRoute
  '/intake/$publishedFormId': typeof IntakePublishedFormIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/staff': typeof AppStaffRoute
  '/mfa/challenge': typeof MfaChallengeRoute
  '/mfa/setup': typeof MfaSetupRoute
  '/staff/activate': typeof StaffActivateRoute
  '/api/intake/$publishedFormId': typeof ApiIntakePublishedFormIdRoute
  '/api/workers/maintenance': typeof ApiWorkersMaintenanceRoute
  '/api/workers/outbox': typeof ApiWorkersOutboxRoute
  '/app/enquiries/$id': typeof AppEnquiriesIdRoute
  '/intake/$publishedFormId/submitted': typeof IntakePublishedFormIdSubmittedRoute
  '/app/enquiries/': typeof AppEnquiriesIndexRoute
  '/intake/$publishedFormId/': typeof IntakePublishedFormIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/settings'
    | '/app/staff'
    | '/mfa/challenge'
    | '/mfa/setup'
    | '/staff/activate'
    | '/api/intake/$publishedFormId'
    | '/api/workers/maintenance'
    | '/api/workers/outbox'
    | '/app/enquiries/$id'
    | '/intake/$publishedFormId/submitted'
    | '/app/enquiries/'
    | '/intake/$publishedFormId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/settings'
    | '/app/staff'
    | '/mfa/challenge'
    | '/mfa/setup'
    | '/staff/activate'
    | '/api/intake/$publishedFormId'
    | '/api/workers/maintenance'
    | '/api/workers/outbox'
    | '/app/enquiries/$id'
    | '/intake/$publishedFormId/submitted'
    | '/app/enquiries'
    | '/intake/$publishedFormId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/settings'
    | '/app/staff'
    | '/mfa/challenge'
    | '/mfa/setup'
    | '/staff/activate'
    | '/api/intake/$publishedFormId'
    | '/api/workers/maintenance'
    | '/api/workers/outbox'
    | '/app/enquiries/$id'
    | '/intake/$publishedFormId/submitted'
    | '/app/enquiries/'
    | '/intake/$publishedFormId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  MfaChallengeRoute: typeof MfaChallengeRoute
  MfaSetupRoute: typeof MfaSetupRoute
  StaffActivateRoute: typeof StaffActivateRoute
  ApiIntakePublishedFormIdRoute: typeof ApiIntakePublishedFormIdRoute
  ApiWorkersMaintenanceRoute: typeof ApiWorkersMaintenanceRoute
  ApiWorkersOutboxRoute: typeof ApiWorkersOutboxRoute
  IntakePublishedFormIdSubmittedRoute: typeof IntakePublishedFormIdSubmittedRoute
  IntakePublishedFormIdIndexRoute: typeof IntakePublishedFormIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/staff': {
      id: '/app/staff'
      path: '/staff'
      fullPath: '/app/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/mfa/challenge': {
      id: '/mfa/challenge'
      path: '/mfa/challenge'
      fullPath: '/mfa/challenge'
      preLoaderRoute: typeof MfaChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa/setup': {
      id: '/mfa/setup'
      path: '/mfa/setup'
      fullPath: '/mfa/setup'
      preLoaderRoute: typeof MfaSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/activate': {
      id: '/staff/activate'
      path: '/staff/activate'
      fullPath: '/staff/activate'
      preLoaderRoute: typeof StaffActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intake/$publishedFormId': {
      id: '/api/intake/$publishedFormId'
      path: '/api/intake/$publishedFormId'
      fullPath: '/api/intake/$publishedFormId'
      preLoaderRoute: typeof ApiIntakePublishedFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workers/maintenance': {
      id: '/api/workers/maintenance'
      path: '/api/workers/maintenance'
      fullPath: '/api/workers/maintenance'
      preLoaderRoute: typeof ApiWorkersMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workers/outbox': {
      id: '/api/workers/outbox'
      path: '/api/workers/outbox'
      fullPath: '/api/workers/outbox'
      preLoaderRoute: typeof ApiWorkersOutboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/enquiries/': {
      id: '/app/enquiries/'
      path: '/enquiries'
      fullPath: '/app/enquiries/'
      preLoaderRoute: typeof AppEnquiriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/enquiries/$id': {
      id: '/app/enquiries/$id'
      path: '/enquiries/$id'
      fullPath: '/app/enquiries/$id'
      preLoaderRoute: typeof AppEnquiriesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/intake/$publishedFormId/': {
      id: '/intake/$publishedFormId/'
      path: '/intake/$publishedFormId'
      fullPath: '/intake/$publishedFormId/'
      preLoaderRoute: typeof IntakePublishedFormIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/$publishedFormId/submitted': {
      id: '/intake/$publishedFormId/submitted'
      path: '/intake/$publishedFormId/submitted'
      fullPath: '/intake/$publishedFormId/submitted'
      preLoaderRoute: typeof IntakePublishedFormIdSubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppEnquiriesIdRoute: typeof AppEnquiriesIdRoute
  AppEnquiriesIndexRoute: typeof AppEnquiriesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
  AppEnquiriesIdRoute: AppEnquiriesIdRoute,
  AppEnquiriesIndexRoute: AppEnquiriesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  MfaChallengeRoute: MfaChallengeRoute,
  MfaSetupRoute: MfaSetupRoute,
  StaffActivateRoute: StaffActivateRoute,
  ApiIntakePublishedFormIdRoute: ApiIntakePublishedFormIdRoute,
  ApiWorkersMaintenanceRoute: ApiWorkersMaintenanceRoute,
  ApiWorkersOutboxRoute: ApiWorkersOutboxRoute,
  IntakePublishedFormIdSubmittedRoute: IntakePublishedFormIdSubmittedRoute,
  IntakePublishedFormIdIndexRoute: IntakePublishedFormIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
