/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppEnquiriesIndexRouteImport } from './routes/app.enquiries.index'
import { Route as AppEnquiriesIdRouteImport } from './routes/app.enquiries.$id'
import { Route as IntakePublishedFormIdIndexRouteImport } from './routes/intake.$publishedFormId.index'
import { Route as IntakePublishedFormIdSubmittedRouteImport } from './routes/intake.$publishedFormId.submitted'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppEnquiriesIndexRoute = AppEnquiriesIndexRouteImport.update({
  id: '/enquiries/',
  path: '/enquiries/',
  getParentRoute: () => AppRoute,
} as any)
const AppEnquiriesIdRoute = AppEnquiriesIdRouteImport.update({
  id: '/enquiries/$id',
  path: '/enquiries/$id',
  getParentRoute: () => AppRoute,
} as any)
const IntakePublishedFormIdIndexRoute =
  IntakePublishedFormIdIndexRouteImport.update({
    id: '/intake/$publishedFormId/',
    path: '/intake/$publishedFormId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const IntakePublishedFormIdSubmittedRoute =
  IntakePublishedFormIdSubmittedRouteImport.update({
    id: '/intake/$publishedFormId/submitted',
    path: '/intake/$publishedFormId/submitted',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/enquiries/$id': typeof AppEnquiriesIdRoute
  '/intake/$publishedFormId/submitted': typeof IntakePublishedFormIdSubmittedRoute
  '/app/enquiries/': typeof AppEnquiriesIndexRoute
  '/intake/$publishedFormId/': typeof IntakePublishedFormIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/enquiries/$id': typeof AppEnquiriesIdRoute
  '/intake/$publishedFormId/submitted': typeof IntakePublishedFormIdSubmittedRoute
  '/app/enquiries': typeof AppEnquiriesIndexRoute
  '/intake/$publishedFormId': typeof IntakePublishedFormIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/enquiries/$id': typeof AppEnquiriesIdRoute
  '/intake/$publishedFormId/submitted': typeof IntakePublishedFormIdSubmittedRoute
  '/app/enquiries/': typeof AppEnquiriesIndexRoute
  '/intake/$publishedFormId/': typeof IntakePublishedFormIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/settings'
    | '/app/enquiries/$id'
    | '/intake/$publishedFormId/submitted'
    | '/app/enquiries/'
    | '/intake/$publishedFormId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/settings'
    | '/app/enquiries/$id'
    | '/intake/$publishedFormId/submitted'
    | '/app/enquiries'
    | '/intake/$publishedFormId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/settings'
    | '/app/enquiries/$id'
    | '/intake/$publishedFormId/submitted'
    | '/app/enquiries/'
    | '/intake/$publishedFormId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  IntakePublishedFormIdSubmittedRoute: typeof IntakePublishedFormIdSubmittedRoute
  IntakePublishedFormIdIndexRoute: typeof IntakePublishedFormIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/enquiries/': {
      id: '/app/enquiries/'
      path: '/enquiries'
      fullPath: '/app/enquiries/'
      preLoaderRoute: typeof AppEnquiriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/enquiries/$id': {
      id: '/app/enquiries/$id'
      path: '/enquiries/$id'
      fullPath: '/app/enquiries/$id'
      preLoaderRoute: typeof AppEnquiriesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/intake/$publishedFormId/': {
      id: '/intake/$publishedFormId/'
      path: '/intake/$publishedFormId'
      fullPath: '/intake/$publishedFormId/'
      preLoaderRoute: typeof IntakePublishedFormIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/$publishedFormId/submitted': {
      id: '/intake/$publishedFormId/submitted'
      path: '/intake/$publishedFormId/submitted'
      fullPath: '/intake/$publishedFormId/submitted'
      preLoaderRoute: typeof IntakePublishedFormIdSubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppEnquiriesIdRoute: typeof AppEnquiriesIdRoute
  AppEnquiriesIndexRoute: typeof AppEnquiriesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppEnquiriesIdRoute: AppEnquiriesIdRoute,
  AppEnquiriesIndexRoute: AppEnquiriesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  IntakePublishedFormIdSubmittedRoute: IntakePublishedFormIdSubmittedRoute,
  IntakePublishedFormIdIndexRoute: IntakePublishedFormIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
